const productsData = [
  {
    id: 1,
    category: "mobiles",
    title: "Apple iPhone 14",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Apple iPhone 14 (128 GB) - Blue",
    price: "89999",
    rating: 4.5,
  },
  {
    id: 5,
    category: "laptops",
    title: "Xiaomi Notebookpro",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3EzeQaC",
    description: "Xiaomi [Smartchoice] Notebookpro ",
    price: "49999",
    rating: 3.5,
  },
  {
    id: 7,
    category: "tablets",
    title: "Xiaomi Pad 6",
    imgSrc: "https://m.media-amazon.com/images/I/71LRY1j6UHL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3ZeNRdY",
    description: "Xiaomi Pad 6| Qualcomm Snapdragon 870| ",
    price: "29999",
    rating: 4.0,
  },
  {
    id: 2,
    category: "mobiles",
    title: "Apple iPhone 12",
    imgSrc: "https://m.media-amazon.com/images/I/71E5zB1qbIL._SL1500_.jpg",
    amazonLink: "https://amzn.to/44MiYi6",
    description: "Apple iPhone 12 (64GB) - White",
    price: "79999",
    rating: 4.5,
  },
  {
    id: 6,
    category: "tablets",
    title: "Lenovo Tab P12 Pro AMOLED",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3RabsdH",
    description:
      "Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3",
    price: "19999",
    rating: 4.2,
  },
  {
    id: 3,
    category: "mobiles",
    title: "Apple iPhone 13",
    imgSrc: "https://m.media-amazon.com/images/I/61VuVU94RnL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3r6XJtv",
    description: "Apple iPhone 13 (128GB) - Blue",
    price: "69999",
    rating: 4.3,
  },
  {
    id: 4,
    category: "laptops",
    title: "MacBook Air 13″ Laptop with M3 chip",
    imgSrc: "https://m.media-amazon.com/images/I/71-D1xCuVwL._SL1500_.jpg",
    amazonLink: "https://amzn.to/44JsK4r",
    description:
      "34.46 cm (13.6″) Liquid Retina Display, 8GB Unified Memory, 256GB SSD Storage, Backlit Keyboard, 1080p FaceTime HD Camera, Touch ID- Midnight",
    price: "29999",
    rating: 4.0,
  },
  {
    id: 9,
    category: "tablets",
    title: "Samsung Galaxy Tab A8",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3Pdsh4F",
    description:
      "Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)",
    price: "49999",
    rating: 3.5,
  },
  {
    id: 8,
    category: "laptops",
    title: "Apple MacBook Air Laptop",
    imgSrc: "https://m.media-amazon.com/images/I/71eXNIDUGjL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3r9rvhm",
    description:
      "Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ",
    price: "89999",
    rating: 4.5,
  },
];
export default productsData;
